# Generated by Django 5.1.15 on 2026-08-19 03:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=2000)),
                ('specialization', models.CharField(help_text='e.g. Strength training, Weight management, Nutrition', max_length=150)),
                ('experience_years', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(80)])),
                ('certifications', models.TextField(blank=True, max_length=2000)),
                ('coaching_approach', models.TextField(blank=True, max_length=2000)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='coach_applications/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_coach_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('disconnected', 'Disconnected')], default='pending', max_length=15)),
                ('message', models.CharField(blank=True, help_text='Optional note sent with the request.', max_length=500)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_connections_received', to=settings.AUTH_USER_MODEL)),
                ('disconnected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_connections_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachDataPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_basic_profile', models.BooleanField(default=False)),
                ('share_height', models.BooleanField(default=False)),
                ('share_weight', models.BooleanField(default=False)),
                ('share_weight_history', models.BooleanField(default=False)),
                ('share_bmi', models.BooleanField(default=False)),
                ('share_activity_level', models.BooleanField(default=False)),
                ('share_fitness_goal', models.BooleanField(default=False)),
                ('share_calorie_target', models.BooleanField(default=False)),
                ('share_fitness_calculations', models.BooleanField(default=False)),
                ('share_progress_information', models.BooleanField(default=False)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='coaching.coachconnection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=2000)),
                ('specialization', models.CharField(max_length=150)),
                ('experience_years', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(80)])),
                ('certifications', models.TextField(blank=True, max_length=2000)),
                ('coaching_approach', models.TextField(blank=True, max_length=2000)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='coach_profiles/')),
                ('is_active', models.BooleanField(default=True, help_text='Admin can suspend a coach by unchecking this. Suspended coaches disappear from the directory.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coachconnection',
            index=models.Index(fields=['user', 'status'], name='coaching_co_user_id_0d817b_idx'),
        ),
        migrations.AddIndex(
            model_name='coachconnection',
            index=models.Index(fields=['coach', 'status'], name='coaching_co_coach_i_9d73fb_idx'),
        ),
    ]
